"""Canonical practical documents so Start/Trial always have a Firestore record."""

CATALOGUE: dict[str, dict] = {
    "grade9_force_basic": {
        "title": "Basic Concepts Associated with Force",
        "description": "Use a spring balance to measure weight and mass of given objects (Activity 4.1).",
        "grade": 9,
        "lessonId": "phy-g9-force-doc",
        "topicId": "topic-g9-force",
        "unitySceneId": "ForceBasicConcepts",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 1,
        "isActive": True,
    },
    "grade9_density_water": {
        "title": "Density of Water 1",
        "description": "Measure mass and volume of water and calculate density.",
        "grade": 9,
        "lessonId": "phy-g9-density-doc",
        "topicId": "topic-g9-density",
        "unitySceneId": "DensityWaterExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 2,
        "isActive": True,
    },
    "grade9_pressure_solid": {
        "title": "Pressure Exerted by Solids",
        "description": "Use a thin wire and sandbags to cut through soap and record Table 5.1.",
        "grade": 9,
        "lessonId": "phy-g9-pressure-solid-doc",
        "topicId": "topic-g9-pressure-solid",
        "unitySceneId": "PressureExertedBySolid",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 3,
        "isActive": True,
    },
    "grade9_reflection_prism": {
        "title": "Dispersion of White Light through a Glass Prism",
        "description": "Select the apparatus, send a thin white beam through a glass prism, and record the ROYGBIV spectrum.",
        "grade": 9,
        "lessonId": "phy-g9-reflection-doc",
        "topicId": "topic-g9-reflection",
        "unitySceneId": "ReflectionPrismExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 4,
        "isActive": True,
    },
    "grade9_lever_15_1": {
        "title": "Lever — Activity 15.1",
        "description": "Set up a first-class lever, measure effort for different load distances, and record the relationship.",
        "grade": 9,
        "lessonId": "phy-g9-lever-doc",
        "topicId": "topic-g9-lever",
        "unitySceneId": "LeverActivity15_1",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 5,
        "isActive": True,
    },
    "grade10_hydrostatic_pressure": {
        "title": "Hydrostatic pressure and its applications",
        "description": "Measure upthrust with a Eureka can and spring balance, then complete the observation table.",
        "grade": 10,
        "lessonId": "phy-g10-hydrostatic-doc",
        "topicId": "topic-g10-hydrostatic",
        "unitySceneId": "HydrostaticPressureExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 6,
        "isActive": True,
    },
    "grade10_work_energy_power": {
        "title": "Work, energy and power",
        "description": "Drop a weight onto clay from different heights and relate potential energy, work and power.",
        "grade": 10,
        "lessonId": "phy-g10-work-energy-doc",
        "topicId": "topic-g10-work-energy",
        "unitySceneId": "WorkEnergyPowerExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 7,
        "isActive": True,
    },
    "grade10_current_electricity": {
        "title": "Current electricity",
        "description": "Build circuits with two dry cells and compare series, parallel and opposing connections.",
        "grade": 10,
        "lessonId": "phy-g10-current-electricity-doc",
        "topicId": "topic-g10-current-electricity",
        "unitySceneId": "CurrentElectricityExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 8,
        "isActive": True,
    },
    "grade10_motion_straight_line": {
        "title": "Motion in a straight line",
        "description": "Time a toy car on a track and compare distance, displacement, speed, velocity and acceleration.",
        "grade": 10,
        "lessonId": "phy-g10-motion-straight-doc",
        "topicId": "topic-g10-motion-straight",
        "unitySceneId": "MotionStraightLineExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 9,
        "isActive": True,
    },
    "grade10_newtons_laws": {
        "title": "Newton's laws of motion",
        "description": "Investigate Newton's first, second and third laws with a trolley, pulley and spring balance.",
        "grade": 10,
        "lessonId": "phy-g10-newtons-laws-doc",
        "topicId": "topic-g10-newtons-laws",
        "unitySceneId": "NewtonsLawsExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 10,
        "isActive": True,
    },
    "grade10_friction": {
        "title": "Friction",
        "description": "Pull a wooden block on sandpaper and compare limiting friction for three contact areas.",
        "grade": 10,
        "lessonId": "phy-g10-friction-doc",
        "topicId": "topic-g10-friction",
        "unitySceneId": "FrictionExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 11,
        "isActive": True,
    },
    "grade10_resultant_force": {
        "title": "Resultant force",
        "description": "Find the resultant of two forces with spring balances, a trolley and pulleys.",
        "grade": 10,
        "lessonId": "phy-g10-resultant-force-doc",
        "topicId": "topic-g10-resultant-force",
        "unitySceneId": "ResultantForceExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 12,
        "isActive": True,
    },
    "grade10_turning_effect": {
        "title": "Turning effect of a force",
        "description": "Investigate the moment of a force with a clamped stick, newton balance and pivot screw.",
        "grade": 10,
        "lessonId": "phy-g10-turning-effect-doc",
        "topicId": "topic-g10-turning-effect",
        "unitySceneId": "TurningEffectExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 13,
        "isActive": True,
    },
    "grade10_equilibrium": {
        "title": "Equilibrium of Forces",
        "description": "Balance a meter ruler under three coplanar parallel forces and compare F1 + F2 with weight W.",
        "grade": 10,
        "lessonId": "phy-g10-equilibrium-doc",
        "topicId": "topic-g10-equilibrium",
        "unitySceneId": "EquilibriumOfForcesExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 14,
        "isActive": True,
    },
    "grade11_waves": {
        "title": "Waves and their applications",
        "description": "Demonstrate formation of a transverse wave with a slinky and observe ribbon motion.",
        "grade": 11,
        "lessonId": "phy-g11-waves-doc",
        "topicId": "topic-g11-waves",
        "unitySceneId": "WavesApplicationsExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 15,
        "isActive": True,
    },
    "grade11_geometrical_optics": {
        "title": "Geometrical Optics",
        "description": "Find the focal length of a concave mirror using a distant object and a white screen.",
        "grade": 11,
        "lessonId": "phy-g11-optics-doc",
        "topicId": "topic-g11-optics",
        "unitySceneId": "GeometricalOpticsExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 16,
        "isActive": True,
    },
    "grade11_heat": {
        "title": "Heat",
        "description": "Illustrate expansion of liquids with a test tube, thin glass tube and a water bath.",
        "grade": 11,
        "lessonId": "phy-g11-heat-doc",
        "topicId": "topic-g11-heat",
        "unitySceneId": "HeatExpansionExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 17,
        "isActive": True,
    },
    "grade11_power_appliances": {
        "title": "Power and Energy of Electric Appliances",
        "description": "Measure voltage and current of electric appliances, then calculate power, energy and kilowatt-hours.",
        "grade": 11,
        "lessonId": "phy-g11-power-appliances-doc",
        "topicId": "topic-g11-power-appliances",
        "unitySceneId": "PowerEnergyAppliancesExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 18,
        "isActive": True,
    },
    "grade11_electronics": {
        "title": "Electronics",
        "description": "Investigate forward bias and reverse bias of a diode using a battery, switch and bulb.",
        "grade": 11,
        "lessonId": "phy-g11-electronics-doc",
        "topicId": "topic-g11-electronics",
        "unitySceneId": "ElectronicsDiodeExperiment",
        "unityBuildUrl": "",
        "maxScore": 100,
        "durationSeconds": 600,
        "demoAllowed": True,
        "demoMaxAttempts": 99,
        "practicalMaxAttempts": 10,
        "order": 19,
        "isActive": True,
    },
}

_ready = False


def ensure_catalogue(db) -> None:
    global _ready
    if _ready:
        return
    for practical_id, spec in CATALOGUE.items():
        ref = db.collection("practicals").document(practical_id)
        snap = ref.get()
        if not snap.exists:
            ref.set(spec)
            continue
        data = snap.to_dict() or {}
        patch = {}
        if not data.get("isActive", False):
            patch["isActive"] = True
        if int(data.get("demoMaxAttempts", 1) or 1) < 10:
            patch["demoMaxAttempts"] = 99
        if int(data.get("practicalMaxAttempts", 1) or 1) < 3:
            patch["practicalMaxAttempts"] = 10
        for field in ("unitySceneId", "lessonId", "topicId", "title"):
            if spec.get(field) and data.get(field) != spec.get(field):
                patch[field] = spec[field]
        if patch:
            ref.update(patch)
    _ready = True


def ensure_practical(db, practical_id: str) -> dict:
    ensure_catalogue(db)
    snap = db.collection("practicals").document(practical_id).get()
    if snap.exists:
        data = snap.to_dict() or {}
        data["id"] = practical_id
        return data
    spec = CATALOGUE.get(practical_id)
    if spec is None:
        return {}
    db.collection("practicals").document(practical_id).set(spec)
    data = dict(spec)
    data["id"] = practical_id
    return data
