// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNM34B3pyUJgV57B5_FJJnM0LPmxuIME',
    appId: '1:336276756841:web:a8cba21f09b1ae3d2d85f8',
    messagingSenderId: '336276756841',
    projectId: 'physicslab-eaa8a',
    authDomain: 'physicslab-eaa8a.firebaseapp.com',
    storageBucket: 'physicslab-eaa8a.firebasestorage.app',
    measurementId: 'G-ZW6C7CQQPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGMZOCCdAL3WVEnBg_mCS-dbo0kfd1sY',
    appId: '1:336276756841:android:30080c842776806c2d85f8',
    messagingSenderId: '336276756841',
    projectId: 'physicslab-eaa8a',
    storageBucket: 'physicslab-eaa8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuOiQOgMA_kAzCdyzlOMlZURkuJqBG5s',
    appId: '1:336276756841:ios:faa7c3dbdfa729d82d85f8',
    messagingSenderId: '336276756841',
    projectId: 'physicslab-eaa8a',
    storageBucket: 'physicslab-eaa8a.firebasestorage.app',
    iosBundleId: 'com.example.physicslab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuOiQOgMA_kAzCdyzlOMlZURkuJqBG5s',
    appId: '1:336276756841:ios:faa7c3dbdfa729d82d85f8',
    messagingSenderId: '336276756841',
    projectId: 'physicslab-eaa8a',
    storageBucket: 'physicslab-eaa8a.firebasestorage.app',
    iosBundleId: 'com.example.physicslab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNM34B3pyUJgV57B5_FJJnM0LPmxuIME',
    appId: '1:336276756841:web:51aefb19a40779e62d85f8',
    messagingSenderId: '336276756841',
    projectId: 'physicslab-eaa8a',
    authDomain: 'physicslab-eaa8a.firebaseapp.com',
    storageBucket: 'physicslab-eaa8a.firebasestorage.app',
    measurementId: 'G-T6P0RWQNRT',
  );
}
