// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PuIPzqUAFxa0N3OQ6te5p33RkL2aaY0',
    appId: '1:855512404287:web:c6bec4384f307154a1038a',
    messagingSenderId: '855512404287',
    projectId: 'physics-learning-platform',
    authDomain: 'physics-learning-platform.firebaseapp.com',
    storageBucket: 'physics-learning-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PuIPzqUAFxa0N3OQ6te5p33RkL2aaY0',
    appId: '1:855512404287:web:c6bec4384f307154a1038a',
    messagingSenderId: '855512404287',
    projectId: 'physics-learning-platform',
    storageBucket: 'physics-learning-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PuIPzqUAFxa0N3OQ6te5p33RkL2aaY0',
    appId: '1:855512404287:web:c6bec4384f307154a1038a',
    messagingSenderId: '855512404287',
    projectId: 'physics-learning-platform',
    storageBucket: 'physics-learning-platform.firebasestorage.app',
    iosBundleId: 'com.example.mobile_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9PuIPzqUAFxa0N3OQ6te5p33RkL2aaY0',
    appId: '1:855512404287:web:c6bec4384f307154a1038a',
    messagingSenderId: '855512404287',
    projectId: 'physics-learning-platform',
    storageBucket: 'physics-learning-platform.firebasestorage.app',
    iosBundleId: 'com.example.mobile_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9PuIPzqUAFxa0N3OQ6te5p33RkL2aaY0',
    appId: '1:855512404287:web:c6bec4384f307154a1038a',
    messagingSenderId: '855512404287',
    projectId: 'physics-learning-platform',
    authDomain: 'physics-learning-platform.firebaseapp.com',
    storageBucket: 'physics-learning-platform.firebasestorage.app',
  );
}
