org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
unityStreamingAssets=
unity.androidNdkPath=D:/unity/Unity Hub/6000.3.22f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidSdkPath=C:\\Users\\ASUS\\AppData\\Local\\Android\\Sdk
unity.androidNdkVersion=27.2.12479018
unity.debugSymbolLevel=none
