org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
unityStreamingAssets=
unity.androidNdkPath=C:/PROGRA~1/Unity/Hub/Editor/60005~1.0F1/Editor/Data/PLAYBA~1/ANDROI~1/NDK
unity.androidSdkPath=C:\\Users\\ASUS\\AppData\\Local\\Android\\Sdk
unity.androidNdkVersion=27.2.12479018
unity.debugSymbolLevel=none
